### ISSUE TITLE
DrMongo Does not detected new collections nor dropped collections

### ISSUE THREAD

**Issue by JuanCrg90** [DrMongo/DrMongo#153] opened 2016-02-01 21:41 UTC
Hi. I'm using DrMongo for check my project database, but i found a little detail, when i insert a new document in a new collection (this still doesn't exists). Dr Mongo don't show me the new collection.

I have restarted the DrMongo App and nothing changed.
I have restarted my application and nothing.

The method that worked for me was update/edit the connection in DrMongo and reconnect me, by this way i can see my new collection.

A similar issue exists when i drop a collection. I was dropped a collection in Robomongo, and in DrMongo the collecction link still exists and a error appears in the console

```
I20160201-15:33:06.750(-6)? > connecting to: mongodb://127.0.0.1:3001/meteor
W20160201-15:33:06.787(-6)? (STDERR)
W20160201-15:33:06.787(-6)? (STDERR) /home/garu/.meteor/packages/npm-mongo/.1.4.39_1.rcnrhy++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:246
W20160201-15:33:06.788(-6)? (STDERR)         throw message;
W20160201-15:33:06.788(-6)? (STDERR)               ^
W20160201-15:33:06.808(-6)? (STDERR) Error: Collection [meteor.videos] not found. [stats.collection]
W20160201-15:33:06.808(-6)? (STDERR)     at server/statsMethods.js:4:13
W20160201-15:33:06.808(-6)? (STDERR)     at /home/garu/.meteor/packages/npm-mongo/.1.4.39_1.rcnrhy++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1196:16
W20160201-15:33:06.809(-6)? (STDERR)     at /home/garu/.meteor/packages/npm-mongo/.1.4.39_1.rcnrhy++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1905:9
W20160201-15:33:06.809(-6)? (STDERR)     at Server.Base._callHandler (/home/garu/.meteor/packages/npm-mongo/.1.4.39_1.rcnrhy++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
W20160201-15:33:06.809(-6)? (STDERR)     at /home/garu/.meteor/packages/npm-mongo/.1.4.39_1.rcnrhy++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
W20160201-15:33:06.809(-6)? (STDERR)     at [object Object].MongoReply.parseBody (/home/garu/.meteor/packages/npm-mongo/.1.4.39_1.rcnrhy++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
W20160201-15:33:06.810(-6)? (STDERR)     at [object Object].<anonymous> (/home/garu/.meteor/packages/npm-mongo/.1.4.39_1.rcnrhy++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
W20160201-15:33:06.810(-6)? (STDERR)     at [object Object].emit (events.js:95:17)
W20160201-15:33:06.810(-6)? (STDERR)     at [object Object].<anonymous> (/home/garu/.meteor/packages/npm-mongo/.1.4.39_1.rcnrhy++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
W20160201-15:33:06.811(-6)? (STDERR)     at [object Object].emit (events.js:98:17)
W20160201-15:33:06.811(-6)? (STDERR)     at Socket.<anonymous> (/home/garu/.meteor/packages/npm-mongo/.1.4.39_1.rcnrhy++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
W20160201-15:33:06.811(-6)? (STDERR)     at Socket.emit (events.js:95:17)
W20160201-15:33:06.812(-6)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20160201-15:33:06.812(-6)? (STDERR)     at Socket.emit (events.js:92:17)
W20160201-15:33:06.812(-6)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20160201-15:33:06.812(-6)? (STDERR)     at emitReadable (_stream_readable.js:423:5)
W20160201-15:33:06.813(-6)? (STDERR)     at readableAddChunk (_stream_readable.js:166:9)
W20160201-15:33:06.813(-6)? (STDERR)     at Socket.Readable.push (_stream_readable.js:128:10)
W20160201-15:33:06.813(-6)? (STDERR)     at TCP.onread (net.js:529:21)
```

The dropped connection disappears when i edit my connection and enter again.

I hope is enough information for replicate the error

Regards.

**Comment by tothradoslav** [comment] 2016-02-02 07:23
thanks for this. It's a duplicate of #152, follow there :)

**Closed as completed by tothradoslav** 2016-02-02 07:23 UTC
Labels: bug
